// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRM54g7bXBVU29bkfGNZrELyZ-rSvjD4',
    appId: '1:524356015267:web:9bfbafcbe3b4eed1631b16',
    messagingSenderId: '524356015267',
    projectId: 'prakflutterfirebase-a8107',
    authDomain: 'prakflutterfirebase-a8107.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-a8107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPWMmDmjoiFOib6dpFLb2FZvWcOuml_pc',
    appId: '1:524356015267:android:44d366c3c59e5bc5631b16',
    messagingSenderId: '524356015267',
    projectId: 'prakflutterfirebase-a8107',
    storageBucket: 'prakflutterfirebase-a8107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2mKOX5JONaMIkuKFHrBNkmvuu0An_xI',
    appId: '1:524356015267:ios:cca4fd9366a87d47631b16',
    messagingSenderId: '524356015267',
    projectId: 'prakflutterfirebase-a8107',
    storageBucket: 'prakflutterfirebase-a8107.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2mKOX5JONaMIkuKFHrBNkmvuu0An_xI',
    appId: '1:524356015267:ios:cca4fd9366a87d47631b16',
    messagingSenderId: '524356015267',
    projectId: 'prakflutterfirebase-a8107',
    storageBucket: 'prakflutterfirebase-a8107.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnRM54g7bXBVU29bkfGNZrELyZ-rSvjD4',
    appId: '1:524356015267:web:f727490e6712e6cd631b16',
    messagingSenderId: '524356015267',
    projectId: 'prakflutterfirebase-a8107',
    authDomain: 'prakflutterfirebase-a8107.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-a8107.appspot.com',
  );
}
